dist: bionic

language: java

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2

stages:
  - name: test
  - name: deploy

before_install:
  - curl -L https://git.io/get_helm.sh | bash
  - helm init --client-only

install: /bin/true

script:
  - |
      if [ "$TRAVIS_BRANCH" = "master" ]; then
        mvn clean deploy -B
        cp README.md target/helm
        cd target/helm
        helm repo index .
        ls -ltr
      else
        mvn clean verify -B
      fi

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: target/helm
  target_branch: gh-pages
  verbose: true
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
