apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "k8s-secret-provisioner.fullname" .}}
  labels:
    app: {{ template "k8s-secret-provisioner.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation
