apiVersion: {{ if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1" }}rbac.authorization.k8s.io/v1{{ else }}rbac.authorization.k8s.io/v1beta1{{ end }}
kind: ClusterRoleBinding
metadata:
  name: {{ template "k8s-secret-provisioner.fullname" . }}
  labels:
    app: {{ template "k8s-secret-provisioner.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation
subjects:
- kind: ServiceAccount
  name: {{ template "k8s-secret-provisioner.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "k8s-secret-provisioner.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
