apiVersion: {{ if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1" }}rbac.authorization.k8s.io/v1{{ else }}rbac.authorization.k8s.io/v1beta1{{ end }}
kind: ClusterRole
metadata:
  name: {{ template "k8s-secret-provisioner.fullname" . }}
  labels:
    app: {{ template "k8s-secret-provisioner.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
  - update
  - patch
